name: Code Quality

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  id-token: write
  issues: write

jobs:
  lint:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Run Linting
        run: npm run lint

  format:
    needs: lint
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Check formatting of project files
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            npm run format:staged
          else
            npm run format
          fi

  build:
    needs: format
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Run build
        run: npm run build

  test:
    needs: build
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Run Unit Test with Coverage
        run: npm run test
      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage

  sonarcloud:
    needs: test
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download coverage reports
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: coverage
      - name: Identify branch type
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/feature-dev" ]]; then
            echo "This is a feature development branch"
            echo "BRANCH_TYPE=feature" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            echo "This is the master branch"
            echo "BRANCH_TYPE=master" >> $GITHUB_ENV
          else
            echo "This is another type of branch"
            echo "BRANCH_TYPE=other" >> $GITHUB_ENV
          fi
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info

  dependabot-build:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Run Linting
        run: npm run lint
      - name: Run Formatting
        run: npm run format
      - name: Run Unit Test with Coverage
        run: npm run test
      - name: Run build
        run: npm run build

